/**
 * Transaction-job state for the private executor.
 *
 * The store is deliberately an injected dependency. A production runtime must
 * provide an atomic, durable implementation (Postgres or equivalent); no
 * ephemeral container memory is accepted as the runtime source of truth.
 */
export const YieldJobStates = [
  "FUNDED",
  "POLICY_ACCEPTED",
  "APPROVAL_SUBMITTED",
  "APPROVED",
  "SUPPLY_SUBMITTED",
  "SUPPLIED",
  "WITHDRAW_SUBMITTED",
  "COMPLETED",
  "REJECTED",
  "RECOVERY_REQUIRED",
] as const;

export type YieldJobState = (typeof YieldJobStates)[number];

export type YieldJob = Readonly<{
  id: string;
  /** Relic marketplace/on-chain job identifier; never generated by the executor. */
  commerceJobId: string;
  /** Stable client key; uniqueness is enforced by the durable store. */
  idempotencyKey: string;
  state: YieldJobState;
  revision: number;
  approvalTxHash: string | null;
  supplyTxHash: string | null;
  withdrawTxHash: string | null;
  recoveryReason: string | null;
  createdAt: Date;
  updatedAt: Date;
}>;

export type CreateYieldJob = Readonly<{
  id: string;
  commerceJobId: string;
  idempotencyKey: string;
  now: Date;
}>;

export type JobTransition = Readonly<{
  id: string;
  expectedRevision: number;
  to: YieldJobState;
  transactionHash?: string;
  recoveryReason?: string;
  now: Date;
}>;

export interface YieldJobStore {
  /**
   * Atomically inserts the job or returns the one already bound to this key.
   * Implementations must put a unique constraint on `idempotencyKey`.
   */
  createOrFind(input: CreateYieldJob): Promise<{ created: boolean; job: YieldJob }>;
  /**
   * Atomically changes state only where both job ID and revision match.
   * A lost race must return null, never overwrite a newer receipt.
   */
  transition(input: JobTransition): Promise<YieldJob | null>;
  get(id: string): Promise<YieldJob | null>;
}

const nextStates: Readonly<Record<YieldJobState, readonly YieldJobState[]>> = {
  FUNDED: ["POLICY_ACCEPTED", "REJECTED"],
  // A prior exact allowance may make the approval call unnecessary.
  POLICY_ACCEPTED: ["APPROVAL_SUBMITTED", "APPROVED", "REJECTED"],
  APPROVAL_SUBMITTED: ["APPROVED", "RECOVERY_REQUIRED"],
  APPROVED: ["SUPPLY_SUBMITTED", "REJECTED"],
  SUPPLY_SUBMITTED: ["SUPPLIED", "RECOVERY_REQUIRED"],
  SUPPLIED: ["WITHDRAW_SUBMITTED", "RECOVERY_REQUIRED"],
  WITHDRAW_SUBMITTED: ["COMPLETED", "RECOVERY_REQUIRED"],
  COMPLETED: [],
  REJECTED: [],
  RECOVERY_REQUIRED: ["APPROVED", "SUPPLIED", "COMPLETED"],
};

const txHash = /^0x[0-9a-fA-F]{64}$/u;

function assertTransition(job: YieldJob, input: JobTransition): void {
  if (!nextStates[job.state].includes(input.to)) {
    throw new Error(`Yield job cannot transition from ${job.state} to ${input.to}`);
  }
  const requiresReceipt = input.to.endsWith("_SUBMITTED");
  if (requiresReceipt && !txHash.test(input.transactionHash ?? "")) {
    throw new Error(`Yield job transition to ${input.to} requires a transaction hash`);
  }
  if (input.to === "RECOVERY_REQUIRED" && !input.recoveryReason?.trim()) {
    throw new Error("Yield job recovery requires a reason");
  }
}

function transitioned(job: YieldJob, input: JobTransition): YieldJob {
  const next = {
    ...job,
    state: input.to,
    revision: job.revision + 1,
    updatedAt: input.now,
    recoveryReason: input.to === "RECOVERY_REQUIRED" ? input.recoveryReason!.trim() : job.recoveryReason,
  } as YieldJob;
  if (input.to === "APPROVAL_SUBMITTED") return { ...next, approvalTxHash: input.transactionHash! };
  if (input.to === "SUPPLY_SUBMITTED") return { ...next, supplyTxHash: input.transactionHash! };
  if (input.to === "WITHDRAW_SUBMITTED") return { ...next, withdrawTxHash: input.transactionHash! };
  return next;
}

/** Test-only model; production must inject a durable YieldJobStore. */
export class InMemoryYieldJobStore implements YieldJobStore {
  private readonly jobs = new Map<string, YieldJob>();
  private readonly idempotency = new Map<string, string>();

  async createOrFind(input: CreateYieldJob): Promise<{ created: boolean; job: YieldJob }> {
    const existingId = this.idempotency.get(input.idempotencyKey);
    if (existingId) return { created: false, job: this.jobs.get(existingId)! };
    const job: YieldJob = Object.freeze({
      id: input.id,
      commerceJobId: input.commerceJobId,
      idempotencyKey: input.idempotencyKey,
      state: "FUNDED",
      revision: 0,
      approvalTxHash: null,
      supplyTxHash: null,
      withdrawTxHash: null,
      recoveryReason: null,
      createdAt: input.now,
      updatedAt: input.now,
    });
    this.jobs.set(job.id, job);
    this.idempotency.set(job.idempotencyKey, job.id);
    return { created: true, job };
  }

  async transition(input: JobTransition): Promise<YieldJob | null> {
    const job = this.jobs.get(input.id);
    if (!job || job.revision !== input.expectedRevision) return null;
    assertTransition(job, input);
    const updated = Object.freeze(transitioned(job, input));
    this.jobs.set(updated.id, updated);
    return updated;
  }

  async get(id: string): Promise<YieldJob | null> {
    return this.jobs.get(id) ?? null;
  }
}
