import type { ChangeRequest, DependencyEdge, EvidenceReference, SystemComponent } from "./types";

export const meridianChangeRequest: ChangeRequest = {
  id: "chg-meridian-reg-surcharge",
  systemName: "Meridian Grid · Billing Core",
  title: "Billing Policy Change",
  requestedChange:
    "Apply a 7% regulatory surcharge only to commercial customers with monthly consumption above 10,000 kWh.",
  affectedComponentId: "regulatory-surcharge-rule",
  objective: "Detect downstream billing, ledger, and reporting regressions.",
  riskSensitivity: "Strict",
};

export const meridianComponents: SystemComponent[] = [
  {
    id: "commercial-invoice-service",
    name: "CommercialInvoiceService",
    type: "service",
    description: "Coordinates commercial invoice calculation and charge instruction assembly.",
    owner: "Billing Platform",
    criticality: "critical",
    sourceReference: "src/billing/services/CommercialInvoiceService.ts:163",
    tags: ["billing", "commercial", "orchestration"],
  },
  {
    id: "regulatory-surcharge-rule",
    name: "RegulatorySurchargeRule",
    type: "rule",
    description: "Applies regulated surcharges to eligible customer invoice lines.",
    owner: "Billing Policy",
    criticality: "high",
    sourceReference: "src/billing/rules/RegulatorySurchargeRule.ts:42",
    tags: ["policy", "surcharge", "change-surface"],
  },
  {
    id: "legacy-volume-discount",
    name: "LegacyVolumeDiscount",
    type: "rule",
    description: "Preserves historical volume discount behavior for large commercial accounts.",
    owner: "Finance Systems",
    criticality: "critical",
    sourceReference: "src/billing/rules/LegacyVolumeDiscount.ts:88",
    tags: ["legacy", "discount", "ledger-adjustment"],
  },
  {
    id: "customer-tier-resolver",
    name: "CustomerTierResolver",
    type: "service",
    description: "Resolves residential, commercial, and enterprise billing tiers.",
    owner: "Customer Systems",
    criticality: "medium",
    sourceReference: "src/customer/CustomerTierResolver.ts:51",
    tags: ["customer", "eligibility"],
  },
  {
    id: "invoice-ledger-writer",
    name: "InvoiceLedgerWriter",
    type: "ledger",
    description: "Commits normalized charge instructions into the invoice ledger.",
    owner: "Finance Systems",
    criticality: "critical",
    sourceReference: "src/ledger/InvoiceLedgerWriter.ts:91",
    tags: ["ledger", "financial-control"],
  },
  {
    id: "finance-reporting-adapter",
    name: "FinanceReportingAdapter",
    type: "adapter",
    description: "Transforms ledger events into finance reporting records.",
    owner: "Financial Reporting",
    criticality: "high",
    sourceReference: "src/reporting/FinanceReportingAdapter.ts:117",
    tags: ["reporting", "reconciliation"],
  },
  {
    id: "commercial-billing-report",
    name: "CommercialBillingReport",
    type: "report",
    description: "Summarizes commercial billing activity for finance review.",
    owner: "Financial Reporting",
    criticality: "high",
    sourceReference: "src/reporting/CommercialBillingReport.ts:74",
    tags: ["report", "commercial"],
  },
  {
    id: "customer-account-repository",
    name: "CustomerAccountRepository",
    type: "repository",
    description: "Provides historical customer account samples and account classification records.",
    owner: "Customer Systems",
    criticality: "medium",
    sourceReference: "src/customer/CustomerAccountRepository.ts:36",
    tags: ["accounts", "history"],
  },
  {
    id: "billing-policy-resolver",
    name: "BillingPolicyResolver",
    type: "service",
    description: "Selects active billing policies and orders rule evaluation for invoice runs.",
    owner: "Billing Platform",
    criticality: "critical",
    sourceReference: "src/billing/services/BillingPolicyResolver.ts:57",
    tags: ["policy", "rule-ordering"],
  },
  {
    id: "invoice-audit-trail",
    name: "InvoiceAuditTrail",
    type: "audit",
    description: "Records invoice decision evidence for compliance and dispute review.",
    owner: "Risk Operations",
    criticality: "high",
    sourceReference: "src/audit/InvoiceAuditTrail.ts:104",
    tags: ["audit", "evidence"],
  },
];

export const meridianDependencies: DependencyEdge[] = [
  { from: "regulatory-surcharge-rule", to: "billing-policy-resolver", relationship: "registered in policy order", critical: true },
  { from: "billing-policy-resolver", to: "commercial-invoice-service", relationship: "feeds active rules", critical: true },
  { from: "commercial-invoice-service", to: "legacy-volume-discount", relationship: "branches into discount reconciliation", critical: true },
  { from: "commercial-invoice-service", to: "invoice-ledger-writer", relationship: "emits charge instructions", critical: true },
  { from: "legacy-volume-discount", to: "invoice-ledger-writer", relationship: "may emit adjustment entry", critical: true },
  { from: "invoice-ledger-writer", to: "finance-reporting-adapter", relationship: "publishes ledger events" },
  { from: "finance-reporting-adapter", to: "commercial-billing-report", relationship: "hydrates report rows" },
  { from: "invoice-ledger-writer", to: "invoice-audit-trail", relationship: "records charge evidence" },
  { from: "customer-account-repository", to: "customer-tier-resolver", relationship: "provides account tier data" },
  { from: "customer-tier-resolver", to: "billing-policy-resolver", relationship: "resolves policy eligibility" },
];

export const evidenceReferences: EvidenceReference[] = [
  {
    id: "ev-surcharge-order",
    sourceReference: "src/billing/rules/RegulatorySurchargeRule.ts:42",
    title: "Surcharge rule order",
    relatedComponentId: "regulatory-surcharge-rule",
    proves: "Surcharge evaluation is invoked before discount-path normalization.",
    severity: "critical",
    relatedAgent: "Red Team",
    excerpt: "Surcharge evaluation is invoked before discount-path normalization.",
  },
  {
    id: "ev-volume-ledger",
    sourceReference: "src/billing/rules/LegacyVolumeDiscount.ts:88",
    title: "Legacy discount ledger behavior",
    relatedComponentId: "legacy-volume-discount",
    proves: "Volume discount reconciliation can emit a secondary ledger adjustment.",
    severity: "critical",
    relatedAgent: "Test Runner",
    excerpt: "Volume discount reconciliation may emit a secondary ledger adjustment.",
  },
  {
    id: "ev-invoice-merge",
    sourceReference: "src/billing/services/CommercialInvoiceService.ts:163",
    title: "Charge instruction merge path",
    relatedComponentId: "commercial-invoice-service",
    proves: "Both charge instructions are passed to the ledger writer for eligible enterprise accounts.",
    severity: "critical",
    relatedAgent: "Mapper",
    excerpt: "Both charge instructions are passed to the ledger writer for eligible enterprise accounts.",
  },
  {
    id: "ev-policy-resolver",
    sourceReference: "src/billing/services/BillingPolicyResolver.ts:57",
    title: "Policy sequencing assumption",
    relatedComponentId: "billing-policy-resolver",
    proves: "Rule sequencing is not normalized around customer tier and volume-discount eligibility.",
    severity: "warning",
    relatedAgent: "Planner",
    excerpt: "Policy resolver applies active rule order before all legacy branch eligibility is closed.",
  },
  {
    id: "ev-reporting-recon",
    sourceReference: "src/reporting/CommercialBillingReport.ts:74",
    title: "Reporting reconciliation surface",
    relatedComponentId: "commercial-billing-report",
    proves: "Duplicate ledger events would flow into commercial billing reports.",
    severity: "warning",
    relatedAgent: "Test Runner",
    excerpt: "Commercial billing report totals are hydrated from ledger event stream.",
  },
  {
    id: "ev-audit-trail",
    sourceReference: "src/audit/InvoiceAuditTrail.ts:104",
    title: "Audit evidence capture",
    relatedComponentId: "invoice-audit-trail",
    proves: "Invoice audit trail captures both emitted charge decisions.",
    severity: "informational",
    relatedAgent: "Verdict",
    excerpt: "Audit trail records each charge instruction with originating rule metadata.",
  },
];
